# EcoPlots Python Library - Observation Mode Demonstration

Welcome to the **EcoPlots Python Library** demonstration notebook. This notebook showcases the key features and capabilities of the library for accessing TERN's EcoPlots data programmatically.

## About EcoPlots

TERN EcoPlots provides access to ecological observation data from systematic site-based surveys and opportunistic surveys across Australia. This Python library offers a clean, Pythonic interface for:

- 🔍 **Discovering** datasets with validated filters
- 📊 **Previewing** results before downloading full datasets
- 🗺️ **Spatial selection** using GeoJSON/WKT
- ⚡ **Async support** for efficient data retrieval
- 💾 **Saving/loading** projects for reproducible workflows

---

## Table of Contents

1. [Setup & Initialization](#setup)
2. [Discovering Datasets](#discovering-datasets)
3. [Applying Filters](#applying-filters)
4. [Retrieving Data](#retrieving-data)
5. [Advanced Features](#advanced-features)

---

<a id="setup"></a>
## 1. Setup & Initialization

### Installation

First, ensure you have the library installed:

```bash
pip install terndata.ecoplots
```

### Choosing a Client: Sync vs Async

The library provides two client options. **Both work identically except for the final `get_data()` call.**

| Client | Best For | When to Use |
|--------|----------|-------------|
| **`EcoPlots`** | Beginners, simple workflows | No `await` needed - simpler syntax |
| **`AsyncEcoPlots`** | Large datasets, production | Use `await` only for `get_data()` - faster |

**Key Point:** All methods (`select()`, `preview()`, `summary()`, etc.) work exactly the same in both clients. Only `get_data()` differs:
- `EcoPlots`: `df = ecoplots.get_data()`
- `AsyncEcoPlots`: `df = await ecoplots.get_data()`

In [5]:
# ===================================================================
# Choose Your Client: Synchronous (simpler) or Asynchronous (advance)
# ===================================================================
# 
# **For beginners**: Use the synchronous `EcoPlots` client (uncomment below)
# - Simpler to use, no need for `await` keywords
# - Works immediately in notebooks and scripts
# - Best for small to medium datasets
#
# **For advanced users**: Use the asynchronous `AsyncEcoPlots` client (default)
# - Faster for large datasets and multiple requests
# - Requires `await` keyword ONLY for get_data()
# - Best for production workflows and large data processing
#
# **Important**: Both clients use identical code except for get_data()!
# - EcoPlots:      df = ecoplots.get_data()
# - AsyncEcoPlots: df = await ecoplots.get_data()
#
# Everything else (select, preview, summary, etc.) works exactly the same!
#
# To switch: Comment out one import and uncomment the other

# Option 1: Synchronous Client (Simpler - uncomment if preferred)
# from terndata.ecoplots import EcoPlots
# ecoplots = EcoPlots()

# Option 2: Asynchronous Client (Faster - currently active)
from terndata.ecoplots import EcoPlots
ecoplots = EcoPlots()
    
# Display the client information
print(ecoplots)

EcoPlots initialized in observations mode.
╔══════════════════════════════════════════════════════════════════════════════╗
║ EcoPlots Observations                                                        ║
║ Version: 1.1.2                                                               ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ No filters applied                                                           ║
╚══════════════════════════════════════════════════════════════════════════════╝

---

<a id="discovering-datasets"></a>
## 2. Discovering Datasets

Let's explore what datasets are available in the EcoPlots portal.

In [6]:
# Get all available datasets
datasets = ecoplots.get_datasources()

print(f"Found {len(datasets)} datasets available")
datasets.head(10)

Found 7 datasets available

,key,uri
0,TERN Ecosystem Surveillance,http://linked.data.gov.au/dataset/ausplots
1,QBEIS,http://linked.data.gov.au/dataset/corveg
2,Three Parks Savanna,http://linked.data.gov.au/dataset/three-parks-...
3,Williams Wet Tropics Vertebrate database,http://linked.data.gov.au/dataset/wet-tropics-...
4,TERN Ecosystem Processes,http://linked.data.gov.au/dataset/tern-ecosyst...
5,TERN AusPlots Forest,http://linked.data.gov.au/dataset/ausplots-forest
6,NSW FMIP,http://linked.data.gov.au/dataset/nsw-fmip

---

<a id="applying-filters"></a>
## 3. Applying Filters

The EcoPlots client uses a **fluent interface** for building queries. You can chain multiple filters together.

### 3.1 Dataset and Feature Type Selection

In [7]:
# Select a dataset and feature type using fluent interface
ecoplots.select(dataset="TERN Ecosystem Surveillance")

# Display current configuration
print(ecoplots)

╔══════════════════════════════════════════════════════════════════════════════╗
║ EcoPlots Observations                                                        ║
║ Version: 1.1.2                                                               ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ Active Filters:                                                              ║
║   • dataset: ['TERN Ecosystem Surveillance']                                 ║
║                                                                              ║
║ Resolved Query Filters: 1                                                    ║
╚══════════════════════════════════════════════════════════════════════════════╝

In [8]:
ecoplots.get_regions(region_type="IBRA7 Bioregions")

                      key                                           uri
0    Flinders Lofty Block  https://linked.data.gov.au/dataset/ibra7/FLB
1               Kanmantoo  https://linked.data.gov.au/dataset/ibra7/KAN
2   Gulf Fall and Uplands  https://linked.data.gov.au/dataset/ibra7/GFU
3        Eyre Yorke Block  https://linked.data.gov.au/dataset/ibra7/EYB
4                 Pilbara  https://linked.data.gov.au/dataset/ibra7/PIL
..                    ...                                           ...
57             Daly Basin  https://linked.data.gov.au/dataset/ibra7/DAB
58       Esperance Plains  https://linked.data.gov.au/dataset/ibra7/ESP
59        Cobar Peneplain  https://linked.data.gov.au/dataset/ibra7/COP
60               Gascoyne  https://linked.data.gov.au/dataset/ibra7/GAS
61       Mount Isa Inlier  https://linked.data.gov.au/dataset/ibra7/MII

[62 rows x 2 columns]

### 3.2 Feature Type Selection

In [9]:
ecoplots.get_feature_types()

                       key                                                uri
0         plant occurrence  http://linked.data.gov.au/def/tern-cv/b311c0d3...
1   land surface substrate  http://linked.data.gov.au/def/tern-cv/aef12cd6...
2           plant specimen  http://linked.data.gov.au/def/tern-cv/2e122e23...
3         plant population  http://linked.data.gov.au/def/tern-cv/ae71c3f6...
4             soil profile  http://linked.data.gov.au/def/tern-cv/80c39b95...
5          plant community  http://linked.data.gov.au/def/tern-cv/ea3a4c64...
6             land surface  http://linked.data.gov.au/def/tern-cv/8282fb22...
7             soil surface  http://linked.data.gov.au/def/tern-cv/06461021...
8                  climate  http://linked.data.gov.au/def/tern-cv/6d40d71e...
9              disturbance  http://linked.data.gov.au/def/tern-cv/7e256d28...
10                landform  http://linked.data.gov.au/def/tern-cv/2cf3ed29...
11        fungi occurrence  http://linked.data.gov.au/def/tern-cv/45a73139...

In [10]:
ecoplots.select(feature_type="plant community")

print(ecoplots)

╔══════════════════════════════════════════════════════════════════════════════╗
║ EcoPlots Observations                                                        ║
║ Version: 1.1.2                                                               ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ Active Filters:                                                              ║
║   • dataset: ['TERN Ecosystem Surveillance']                                 ║
║   • feature_type: ['plant community']                                        ║
║                                                                              ║
║ Resolved Query Filters: 2                                                    ║
╚══════════════════════════════════════════════════════════════════════════════╝

### 3.3 Region and Region Type Selection

In [8]:
ecoplots.get_region_types()

,key,uri
0,Indigenous Areas,https://linked.data.gov.au/dataset/asgsed3/IARE
1,Indigenous Locations,https://linked.data.gov.au/dataset/asgsed3/ILOC
2,Indigenous Regions,https://linked.data.gov.au/dataset/asgsed3/IREG
3,Local Government Areas,https://linked.data.gov.au/dataset/asgsed3/LGA...
4,States and Territories,https://linked.data.gov.au/dataset/asgsed3/STE
5,NRM regions,https://linked.data.gov.au/dataset/ausnrm2023
6,IBRA7 Bioregions,https://linked.data.gov.au/dataset/ibra7
7,IBRA7 Subregions,https://linked.data.gov.au/dataset/ibra7/subre...
8,WWF ecoregions,https://linked.data.gov.au/dataset/wwf2011
9,Terrestrial CAPAD regions,https://linked.data.gov.au/dataset/auscapad2022

In [11]:
regions = ecoplots.get_regions("States and Territories")
regions.head(10)

                  key                                               uri
0     South Australia  https://linked.data.gov.au/dataset/asgsed3/STE/4
1   Western Australia  https://linked.data.gov.au/dataset/asgsed3/STE/5
2  Northern Territory  https://linked.data.gov.au/dataset/asgsed3/STE/7
3          Queensland  https://linked.data.gov.au/dataset/asgsed3/STE/3
4     New South Wales  https://linked.data.gov.au/dataset/asgsed3/STE/1
5            Tasmania  https://linked.data.gov.au/dataset/asgsed3/STE/6
6            Victoria  https://linked.data.gov.au/dataset/asgsed3/STE/2

In [12]:
# Apply region
ecoplots.select(region_type="WWF ecoregions", region="Pilbara shrublands")

print(ecoplots)

╔══════════════════════════════════════════════════════════════════════════════╗
║ EcoPlots Observations                                                        ║
║ Version: 1.1.2                                                               ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ Active Filters:                                                              ║
║   • dataset: ['TERN Ecosystem Surveillance']                                 ║
║   • feature_type: ['plant community']                                        ║
║   • region_type: ['WWF ecoregions']                                          ║
║   • region: ['Pilbara shrublands']                                           ║
║                                                                              ║
║ Resolved Query Filters: 4                                                    ║
╚══════════════════════════════════════════════════════════════════════════════╝

### 3.4 View Current Filters

Check what filters are currently active.

In [11]:
# Get current filter configuration
filters = ecoplots.get_filter()
print("Active filters:")
for key, value in filters.items():
    print(f"  • {key}: {value}")

print("\n{}\n".format("="*79))

query_filters = ecoplots.get_api_query_filters()
print("Active API Query filters:")
for key, value in query_filters.items():
    print(f"  • {key}: {value}")

Active filters:
  • dataset: ['TERN Ecosystem Surveillance']
  • feature_type: ['plant community']
  • region_type: ['WWF ecoregions']
  • region: ['Pilbara shrublands']

===============================================================================

Active API Query filters:
  • dataset: ['http://linked.data.gov.au/dataset/ausplots']
  • feature_type: ['http://linked.data.gov.au/def/tern-cv/ea3a4c64-dac3-4660-809a-8ad5ced8997b']
  • region: ['https://linked.data.gov.au/dataset/wwf2011/11753']
  • region_type: ['https://linked.data.gov.au/dataset/wwf2011']

---

<a id="retrieving-data"></a>
## 4. Retrieving Data

### 4.1 Get Summary
Get a summary of dataset based on applied filters.

In [13]:
ecoplots.summary()

              metric  count
0       observations   1027
1            dataset      1
2       feature_type      1
3  observed_property     21
4               site     36
5         site_visit     51

### 4.2 Get Data Preview

Get a small subset of dataset based on applied filters.

In [14]:
# Get a preview (first page) of the data
preview_df = ecoplots.preview()
print(f"Preview contains {len(preview_df)} records")
preview_df.head()

Preview contains 1 records

,datasetTitle,projectTitle,siteName,latitude_Degree,longitude_Degree,siteVisitName,siteVisitStartDate,siteVisitEndDate,featureType,featureId,...,averageVegetationHeightUpperStratum_metre,averageVegetationHeightUpperStratumResultTime,averageVegetationHeightUpperStratumMethod,foliageProjectiveCoverMidStratum_percent,foliageProjectiveCoverMidStratumResultTime,foliageProjectiveCoverMidStratumMethod,averageVegetationHeightMidStratum_metre,averageVegetationHeightMidStratumResultTime,averageVegetationHeightMidStratumMethod,geometry
0,TERN Ecosystem Surveillance,N/A,WAAPIL0004,-21.39493,117.1698,20150830,2015-08-30T16:52:34,2015-08-30T16:52:34,plant community,http://linked.data.gov.au/dataset/ausplots/sit...,...,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,POINT (117.1698 -21.39493)

### 4.3 Get Full Dataset

Retrieve the complete dataset based on your filters.

In [15]:
# ============================================================
# Retrieving Data: Sync vs Async
# ============================================================
#
# If using **synchronous** EcoPlots client:
df = ecoplots.get_data()
#
# If using **asynchronous** AsyncEcoPlots client (current):
# df = await ecoplots.get_data()
#
# Note: `await` is only needed for AsyncEcoPlots!
# ============================================================

# Retrieve data asynchronously (returns GeoDataFrame)
# df = await ecoplots.get_data()

print(f"Retrieved {len(df)} records")
print(f"Columns: {', '.join(df.columns)}")
df.head()

Retrieved 51 records
Columns: datasetTitle, projectTitle, siteName, latitude_Degree, longitude_Degree, siteVisitName, siteVisitStartDate, siteVisitEndDate, featureType, featureId, scientificName, vegetationStructureDescription, comment, vegetationCondition, vegetationConditionResultTime, vegetationConditionMethod, nvisHeightClassDerivation, nvisHeightClassDerivationResultTime, nvisHeightClassDerivationMethod, nvisStructuralFormationDerivation, nvisStructuralFormationDerivationResultTime, nvisStructuralFormationDerivationMethod, vegetationCommunityExtent_metre, vegetationCommunityExtentResultTime, vegetationCommunityExtentMethod, nvisMajorVegetationGroupDerivation, nvisMajorVegetationGroupDerivationResultTime, nvisMajorVegetationGroupDerivationMethod, nvisCoverClassDerivation, nvisCoverClassDerivationResultTime, nvisCoverClassDerivationMethod, nvisSubFormationDerivation, nvisSubFormationDerivationResultTime, nvisSubFormationDerivationMethod, averageVegetationHeightGroundStratum_metre, averageVegetationHeightGroundStratumResultTime, averageVegetationHeightGroundStratumMethod, massFloweringEventExist, massFloweringEventExistResultTime, massFloweringEventExistMethod, nvisClassDerivation, nvisClassDerivationResultTime, nvisClassDerivationMethod, nvisAssociationDerivation, nvisAssociationDerivationResultTime, nvisAssociationDerivationMethod, vegetationCommunityAssociation, vegetationCommunityAssociationResultTime, vegetationCommunityAssociationMethod, nvisMajorVegetationSubgroupDerivation, nvisMajorVegetationSubgroupDerivationResultTime, nvisMajorVegetationSubgroupDerivationMethod, canopyCoverUpperStratum_percent, canopyCoverUpperStratumResultTime, canopyCoverUpperStratumMethod, nvisBroadFloristicFormationDerivation, nvisBroadFloristicFormationDerivationResultTime, nvisBroadFloristicFormationDerivationMethod, vegetationCommunitySubAssociation, vegetationCommunitySubAssociationResultTime, vegetationCommunitySubAssociationMethod, nvisSubAssociationDerivation, nvisSubAssociationDerivationResultTime, nvisSubAssociationDerivationMethod, percentageCoverGroundStratum_percent, percentageCoverGroundStratumResultTime, percentageCoverGroundStratumMethod, averageVegetationHeightUpperStratum_metre, averageVegetationHeightUpperStratumResultTime, averageVegetationHeightUpperStratumMethod, foliageProjectiveCoverMidStratum_percent, foliageProjectiveCoverMidStratumResultTime, foliageProjectiveCoverMidStratumMethod, averageVegetationHeightMidStratum_metre, averageVegetationHeightMidStratumResultTime, averageVegetationHeightMidStratumMethod, geometry

,datasetTitle,projectTitle,siteName,latitude_Degree,longitude_Degree,siteVisitName,siteVisitStartDate,siteVisitEndDate,featureType,featureId,...,averageVegetationHeightUpperStratum_metre,averageVegetationHeightUpperStratumResultTime,averageVegetationHeightUpperStratumMethod,foliageProjectiveCoverMidStratum_percent,foliageProjectiveCoverMidStratumResultTime,foliageProjectiveCoverMidStratumMethod,averageVegetationHeightMidStratum_metre,averageVegetationHeightMidStratumResultTime,averageVegetationHeightMidStratumMethod,geometry
0,TERN Ecosystem Surveillance,N/A,WAAPIL0004,-21.39493,117.1698,20150830,2015-08-30T16:52:34,2015-08-30T16:52:34,plant community,http://linked.data.gov.au/dataset/ausplots/sit...,...,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,POINT (117.1698 -21.39493)
1,TERN Ecosystem Surveillance,N/A,WAAPIL0006,-21.56424,117.0591,20150901,2015-09-01T09:49:59,2015-09-01T09:49:59,plant community,http://linked.data.gov.au/dataset/ausplots/sit...,...,3.37,2015-09-01T00:00:00,http://linked.data.gov.au/def/ausplots-cv/9088...,0.1,2015-09-01T00:00:00,http://linked.data.gov.au/def/ausplots-cv/9088...,1.0,2015-09-01T00:00:00,http://linked.data.gov.au/def/ausplots-cv/9088...,POINT (117.0591 -21.56424)
2,TERN Ecosystem Surveillance,N/A,WAAPIL0003,-21.54110,117.0570,20150830,2015-08-30T11:01:10,2015-08-30T11:01:10,plant community,http://linked.data.gov.au/dataset/ausplots/sit...,...,2.29,2015-08-30T00:00:00,http://linked.data.gov.au/def/ausplots-cv/9088...,N/A,N/A,N/A,N/A,N/A,N/A,POINT (117.057 -21.5411)
3,TERN Ecosystem Surveillance,N/A,WAAPIL0007,-21.67714,116.9740,20150901,2015-09-01T14:39:13,2015-09-01T14:39:13,plant community,http://linked.data.gov.au/dataset/ausplots/sit...,...,1.87,2015-09-01T00:00:00,http://linked.data.gov.au/def/ausplots-cv/9088...,10.02,2015-09-01T00:00:00,http://linked.data.gov.au/def/ausplots-cv/9088...,1.5,2015-09-01T00:00:00,http://linked.data.gov.au/def/ausplots-cv/9088...,POINT (116.974 -21.67714)
4,TERN Ecosystem Surveillance,N/A,WAAPIL0008,-21.66288,117.7047,20150902,2015-09-02T13:49:40,2015-09-02T13:49:40,plant community,http://linked.data.gov.au/dataset/ausplots/sit...,...,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,POINT (117.7047 -21.66288)

In [4]:
%pip install aiohttp ipyleaflet pyarrow

Requirement already satisfied: aiohttp in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (3.14.3)
Requirement already satisfied: ipyleaflet in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (0.20.0)
Requirement already satisfied: pyarrow in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (25.0.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from aiohttp) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from aiohttp) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from aiohttp) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from aiohttp) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from aiohttp) (6.8.0)
Requirement already satisfied: propcache>=0.2.0 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from aiohttp) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from aiohttp) (1.25.1)
Requirement already satisfied: idna>=2.0 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from yarl<2.0,>=1.17.0->aiohttp) (3.19)
Requirement already satisfied: branca>=0.5.0 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from ipyleaflet) (0.8.2)
Requirement already satisfied: ipywidgets<9,>=7.6.0 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from ipyleaflet) (8.1.9)
Requirement already satisfied: jupyter-leaflet<0.21,>=0.20 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from ipyleaflet) (0.20.0)
Requirement already satisfied: traittypes<3,>=0.2.1 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from ipyleaflet) (0.2.3)
Requirement already satisfied: xyzservices>=2021.8.1 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from ipyleaflet) (2026.9.1)
Requirement already satisfied: comm>=0.1.3 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from ipywidgets<9,>=7.6.0->ipyleaflet) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from ipywidgets<9,>=7.6.0->ipyleaflet) (9.17.1)
Requirement already satisfied: traitlets>=4.3.1 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from ipywidgets<9,>=7.6.0->ipyleaflet) (5.16.1)
Requirement already satisfied: widgetsnbextension~=4.0.16 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from ipywidgets<9,>=7.6.0->ipyleaflet) (4.0.16)
Requirement already satisfied: jupyterlab_widgets~=3.0.17 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from ipywidgets<9,>=7.6.0->ipyleaflet) (3.0.17)
Requirement already satisfied: jinja2>=3 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from branca>=0.5.0->ipyleaflet) (3.1.6)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyleaflet) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.2.2)
Requirement already satisfied: pexpect>4.6 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyleaflet) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyleaflet) (3.0.53)
Requirement already satisfied: psutil>=7 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyleaflet) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyleaflet) (2.21.0)
Requirement already satisfied: stack_data>=0.6.0 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.6.3)
Requirement already satisfied: wcwidth>=0.1.4 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.8.3)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from jedi>=0.18.2->ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.8.7)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from jinja2>=3->branca>=0.5.0->ipyleaflet) (3.0.3)
Requirement already satisfied: ptyprocess>=0.5 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from pexpect>4.6->ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyleaflet) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyleaflet) (3.0.2)
Requirement already satisfied: pure-eval in /Users/uqjsanc2/projects/R_I_Week_workshop/.venv2/lib/python3.13/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.2.4)

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

---

<a id="advanced-features"></a>
## 5. Advanced Features

### 5.1 Flexible Filter Selection

The EcoPlots library supports multiple ways to apply filters, giving you the flexibility to choose the approach that best fits your workflow. Whether you prefer precision with direct API URIs, readability with human-friendly names, or convenience with smart typo correction (with warnings), the library has you covered!

In [16]:
# ============================================================
# Multiple Ways to Apply Filters
# ============================================================
# The library is flexible and supports various filtering approaches:
# 1. Direct API URIs (for precision)
# 2. Human-readable names (we'll resolve them)
# 3. Method chaining (for fluent queries)
# 4. Smart correction (common typos handled with warnings)
# ============================================================

# Clear previous selections to start fresh
ecoplots.clear()

# ───────────────────────────────────────────────────────────
# 1. Using Direct API URIs (Most Precise)
# ───────────────────────────────────────────────────────────
# Use actual EcoPlots API endpoint URIs for exact filtering
ecoplots.select({
    "dataset": [
        "http://linked.data.gov.au/dataset/ausplots-forest"
    ],
    "project": [
        "http://linked.data.gov.au/dataset/ausplots-forest/dataset-fuel-load"
    ],
})

# ───────────────────────────────────────────────────────────
# 2. Method Chaining (Fluent Interface)
# ───────────────────────────────────────────────────────────
# Chain multiple select() calls together for readable queries
ecoplots.select(site_id="NSFNNC0002").select(feature_type="plant litter")

# ───────────────────────────────────────────────────────────
# 3. Human-Readable Names + Smart Typo Correction
# ───────────────────────────────────────────────────────────
# Use natural names - the library will handle common typos
# Note: Corrections will display a warning showing what was fixed
ecoplots.select({
    "region_type": "NRM regions",
    "region": "North coasy",  # Typo: will be auto-corrected with a warning
})

# View the final configuration
print(ecoplots)

╔══════════════════════════════════════════════════════════════════════════════╗
║ EcoPlots Observations                                                        ║
║ Version: 1.1.2                                                               ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ Active Filters:                                                              ║
║   • dataset: ['TERN AusPlots Forest']                                        ║
║   • project: ['Forest Fuel Survey']                                          ║
║   • site_id: ['NSFNNC0002']                                                  ║
║   • feature_type: ['plant litter']                                           ║
║   • region_type: ['NRM regions']                                             ║
║   • region: ['North Coast']                                                  ║
║                                                                              ║
║ Resolved Query Filters: 6                                                    ║
╚══════════════════════════════════════════════════════════════════════════════╝

⚠️  Warning: Value 'North coasy' for facet 'region' corrected to 'North Coast'.

### 5.2 Applying Spatial Filters

Apply spatial filter using interactive widget

In [15]:
# Apply regional filters using dictionary syntax
ecoplots.select_spatial()

VBox(children=(HTML(value='\n        <style>\n          /* Hide Leaflet Draw edit/remove toolbar and actions *…

In [18]:
print(ecoplots)

╔══════════════════════════════════════════════════════════════════════════════╗
║ EcoPlots Observations                                                        ║
║ Version: 1.1.2                                                               ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ Active Filters:                                                              ║
║   • dataset: ['TERN AusPlots Forest']                                        ║
║   • project: ['Forest Fuel Survey']                                          ║
║   • site_id: ['NSFNNC0002']                                                  ║
║   • feature_type: ['plant litter']                                           ║
║   • region_type: ['NRM regions']                                             ║
║   • region: ['North Coast']                                                  ║
║                                                                              ║
║ Resolved Query Filters: 6                                                    ║
╚══════════════════════════════════════════════════════════════════════════════╝

### 5.3 Data Summary

Get a quick summary of available data with current filters.

In [19]:
# Get summary statistics for the filtered dataset
summary = ecoplots.summary()
summary

              metric  count
0       observations     89
1            dataset      1
2       feature_type      1
3  observed_property     14
4               site      1
5         site_visit      1

### 5.4 Preview Before Downloading

Preview a small sample of data before retrieving the full dataset.

In [20]:
# Get a preview (first page) of the data
preview_df = ecoplots.preview()
print(f"Preview contains {len(preview_df)} records")
preview_df.head()

Preview contains 1 records

,datasetTitle,projectTitle,siteName,latitude_Degree,longitude_Degree,elevation_Metre,siteVisitName,siteVisitStartDate,siteVisitEndDate,featureType,...,annualMeanFineLitterfallRate_number,annualMeanFineLitterfallRateResultTime,annualMeanFineLitterfallRateMethod,annualMeanCoarseLitterfallMass_tonnePerHectareYear,annualMeanCoarseLitterfallMassResultTime,annualMeanCoarseLitterfallMassMethod,annualMeanCoarseLitterfallRate_number,annualMeanCoarseLitterfallRateResultTime,annualMeanCoarseLitterfallRateMethod,geometry
0,TERN AusPlots Forest,Forest Fuel Survey,NSFNNC0002,-31.2421,152.4609,631,20141211,2014-12-11T00:00:01,2014-12-11T00:00:01,plant litter,...,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,POINT (152.4609 -31.2421)

### 5.5 Detailed Data Inspection

Display data with all columns visible for detailed inspection.

In [21]:
# Display with all columns visible
import pandas as pd
from IPython.display import display

df = ecoplots.get_data()
print(f"Data contains {len(df)} records")
with pd.option_context('display.max_columns', None):
    display(df)

Data contains 6 records

,datasetTitle,projectTitle,siteName,latitude_Degree,longitude_Degree,elevation_Metre,siteVisitName,siteVisitStartDate,siteVisitEndDate,featureType,featureId,parentFeatureId,scientificName,leafLitterfallSampleSize,fineLitterSampleSize,plantFuelMatterType,plantLitterfallProductionSampleSize,plantFuelDryBiomass_gramPerSquareMetre,plantFuelDryBiomassResultTime,plantFuelDryBiomassMethod,plantWaterContent_percent,plantWaterContentResultTime,plantWaterContentMethod,fuelLoadMean_tonnePerHectare,fuelLoadMeanResultTime,fuelLoadMeanMethod,meanLeafLitterfallProduction_gramPerSquareMetre,meanLeafLitterfallProductionResultTime,meanLeafLitterfallProductionMethod,meanFineLitterStock_gramPerSquareMetre,meanFineLitterStockResultTime,meanFineLitterStockMethod,meanFineLitterProduction_gramPerSquareMetre,meanFineLitterProductionResultTime,meanFineLitterProductionMethod,meanFineLitterTurnover_unitless,meanFineLitterTurnoverResultTime,meanFineLitterTurnoverMethod,meanLeafLitterfallStock_gramPerSquareMetre,meanLeafLitterfallStockResultTime,meanLeafLitterfallStockMethod,meanLeafLitterfallTurnover_unitless,meanLeafLitterfallTurnoverResultTime,meanLeafLitterfallTurnoverMethod,meanPlantDuffDepth_centimetre,meanPlantDuffDepthResultTime,meanPlantDuffDepthMethod,annualMeanFineLitterfallMass_tonnePerHectareYear,annualMeanFineLitterfallMassResultTime,annualMeanFineLitterfallMassMethod,annualMeanFineLitterfallRate_number,annualMeanFineLitterfallRateResultTime,annualMeanFineLitterfallRateMethod,annualMeanCoarseLitterfallMass_tonnePerHectareYear,annualMeanCoarseLitterfallMassResultTime,annualMeanCoarseLitterfallMassMethod,annualMeanCoarseLitterfallRate_number,annualMeanCoarseLitterfallRateResultTime,annualMeanCoarseLitterfallRateMethod,geometry
0,TERN AusPlots Forest,Forest Fuel Survey,NSFNNC0002,-31.2421,152.4609,631,20141211,2014-12-11T00:00:01,2014-12-11T00:00:01,plant litter,http://linked.data.gov.au/dataset/ausplots-for...,http://linked.data.gov.au/dataset/ausplots-for...,N/A,8.0,12.0,Herb,4.0,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,506.067804,2014-12-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/59ad...,941.598807,2014-12-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/59ad...,81.462702,2014-12-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/59ad...,0.086515,2014-12-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/59ad...,6112.125,2014-12-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/59ad...,0.082797,2014-12-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/59ad...,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,POINT (152.4609 -31.2421)
1,TERN AusPlots Forest,Forest Fuel Survey,NSFNNC0002,-31.2421,152.4609,631,20141211,2014-12-11T00:00:01,2014-12-11T00:00:01,plant litter,http://linked.data.gov.au/dataset/ausplots-for...,http://linked.data.gov.au/dataset/ausplots-for...,N/A,8.0,12.0,Grass,4.0,478.25,2014-12-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/59ad...,0.65,2014-12-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/59ad...,1.675,2014-12-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/59ad...,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,POINT (152.4609 -31.2421)
2,TERN AusPlots Forest,Forest Fuel Survey,NSFNNC0002,-31.2421,152.4609,631,20141211,2014-12-11T00:00:01,2014-12-11T00:00:01,plant litter,http://linked.data.gov.au/dataset/ausplots-for...,http://linked.data.gov.au/dataset/ausplots-for...,N/A,8.0,12.0,Herb,4.0,4.25,2014-12-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/59ad...,0.64,2014-12-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/59ad...,0.0,2014-12-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/59ad...,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,POINT (152.4609 -31.2421)
3,TERN AusPlots Forest,Forest Fuel Survey,NSFNNC0002,-31.2421,152.4609,631,20141211,2014-12-11T00:00:01,2014-12-11T00:00:01,plant litter,http://linked.data.gov.au/dataset/ausplots-for...,http://linked.data.gov.au/dataset/ausplots-for...,N/A,8.0,12.0,Litter,4.0,6112.25,2014-12-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/59ad...,0.57,2014-12-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/59ad...,26.575,2014-12-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/59ad...,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,POINT (152.4609 -31.2421)
4,TERN AusPlots Forest,Forest Fuel Survey,NSFNNC0002,-31.2421,152.4609,631,20141211,2014-12-11T00:00:01,2014-12-11T00:00:01,plant litter,http://linked.data.gov.au/dataset/ausplots-for...,http://linked.data.gov.au/dataset/ausplots-for...,N/A,8.0,12.0,Vine,4.0,62.0,2014-12-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/59ad...,0.5,2014-12-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/59ad...,0.325,2014-12-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/59ad...,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,POINT (152.4609 -31.2421)
5,TERN AusPlots Forest,Forest Fuel Survey,NSFNNC0002,-31.2421,152.4609,631,20141211,2014-12-11T00:00:01,2014-12-11T00:00:01,plant litter,http://linked.data.gov.au/dataset/ausplots-for...,http://linked.data.gov.au/dataset/ausplots-for...,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,1.75,2014-11-12T00:00:00,http://linked.data.gov.au/def/ausplots-cv/59ad...,5.075,2014-11-12T00:00:00,http://linked.data.gov.au/def/ausplots-cv/59ad...,0.193396,2014-11-12T00:00:00,http://linked.data.gov.au/def/ausplots-cv/59ad...,0.814627,2014-11-12T00:00:00,http://linked.data.gov.au/def/ausplots-cv/59ad...,0.364974,2014-11-12T00:00:00,http://linked.data.gov.au/def/ausplots-cv/59ad...,POINT (152.4609 -31.2421)

### 5.6 Get Data as Geojson

Display data in `geojson` format

In [22]:
geojson_data = ecoplots.get_data(dformat="geojson")

import json
print(json.dumps(geojson_data, indent=2))

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "id": "http://linked.data.gov.au/dataset/ausplots-forest/site-nsfnnc0002",
      "properties": {
        "dataset": {
          "dataset.title": "TERN AusPlots Forest",
          "dataset.link": "https://ecoplots.tern.org.au/search?dataset=ausplots-forest",
          "dataset.attributes": {}
        },
        "site": {
          "site.name": "NSFNNC0002",
          "site.link": "https://ecoplots.tern.org.au/search?dataset=ausplots-forest&site_id=ausplots-forest%2Fsite-nsfnnc0002",
          "site.attributes": {
            "permanentPlot": true,
            "plotWidth": 101.0,
            "existingPlotCustodian": "Forestry Corporation NSW, Willi Willi National Park",
            "plotArea": 10100.0,
            "plotShape": "rectangle",
            "plotLength": 100.0
          }
        },
        "siteVisit": [
          {
            "siteVisit.id": "http://linked.data.gov.au/dataset/ausplots-forest/sv-nsfnnc0002-fuel",
            "siteVisit.name": "20141211",
            "siteVisit.date": "2014-12-11T00:00:01",
            "siteVisit.link": "https://ecoplots.tern.org.au/search?dataset=ausplots-forest&site_id=ausplots-forest%2Fsite-nsfnnc0002&site_visit_id=ausplots-forest%2Fsv-nsfnnc0002-fuel",
            "siteVisit.attributes": {},
            "featureOfInterest": [
              {
                "foi.id": "http://linked.data.gov.au/dataset/ausplots-forest/plant_litter_id-2",
                "foi.link": "https://ecoplots.tern.org.au/search?dataset=ausplots-forest&site_id=ausplots-forest%2Fsite-nsfnnc0002&feature_type=plant-litter",
                "foi.type": "plant litter",
                "foi.attributes": {
                  "plantLitterfallProductionSampleSize": {
                    "value": 4,
                    "unit": "Number",
                    "attribute": "plant litterfall production sample size"
                  },
                  "leafLitterfallSampleSize": {
                    "value": 8,
                    "unit": "Number",
                    "attribute": "leaf litterfall sample size"
                  },
                  "plantFuelMatterType": {
                    "value": "Herb",
                    "unit": null,
                    "attribute": "plant fuel matter type"
                  },
                  "fineLitterSampleSize": {
                    "value": 12,
                    "unit": "Number",
                    "attribute": "fine litter sample size"
                  }
                },
                "foi.observations": {
                  "meanFineLitterProduction": [
                    {
                      "observableProperty": "mean fine litter production",
                      "value": 81.46270161,
                      "unit": "Gram per Square Metre",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "mean fine litter production",
                      "value": 81.46270161,
                      "unit": "Gram per Square Metre",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    }
                  ],
                  "meanFineLitterStock": [
                    {
                      "observableProperty": "mean fine litter stock",
                      "value": 941.598807,
                      "unit": "Gram per Square Metre",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "mean fine litter stock",
                      "value": 941.598807,
                      "unit": "Gram per Square Metre",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    }
                  ],
                  "meanFineLitterTurnover": [
                    {
                      "observableProperty": "mean fine litter turnover",
                      "value": 0.086515298,
                      "unit": "Unitless",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "mean fine litter turnover",
                      "value": 0.086515298,
                      "unit": "Unitless",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    }
                  ],
                  "meanLeafLitterfallProduction": [
                    {
                      "observableProperty": "mean leaf litterfall production",
                      "value": 506.0678043,
                      "unit": "Gram per Square Metre",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "mean leaf litterfall production",
                      "value": 506.0678043,
                      "unit": "Gram per Square Metre",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    }
                  ],
                  "meanLeafLitterfallStock": [
                    {
                      "observableProperty": "mean leaf litterfall stock",
                      "value": 6112.125,
                      "unit": "Gram per Square Metre",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "mean leaf litterfall stock",
                      "value": 6112.125,
                      "unit": "Gram per Square Metre",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    }
                  ],
                  "meanLeafLitterfallTurnover": [
                    {
                      "observableProperty": "mean leaf litterfall turnover",
                      "value": 0.082797358,
                      "unit": "Unitless",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "mean leaf litterfall turnover",
                      "value": 0.082797358,
                      "unit": "Unitless",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    }
                  ]
                }
              },
              {
                "foi.id": "http://linked.data.gov.au/dataset/ausplots-forest/plant_litter_id-5",
                "foi.link": "https://ecoplots.tern.org.au/search?dataset=ausplots-forest&top_parent_site_id=ausplots-forest%2Fsite-nsfnnc0002&site_id=ausplots-forest%2Fsite-nsfnnc0002&feature_type=plant-litter",
                "foi.type": "plant litter",
                "metadata.link": null,
                "foi.attributes": {
                  "plantLitterfallProductionSampleSize": {
                    "value": 4,
                    "unit": "Number",
                    "attribute": "plant litterfall production sample size"
                  },
                  "leafLitterfallSampleSize": {
                    "value": 8,
                    "unit": "Number",
                    "attribute": "leaf litterfall sample size"
                  },
                  "plantFuelMatterType": {
                    "value": "Grass",
                    "unit": null,
                    "attribute": "plant fuel matter type"
                  },
                  "fineLitterSampleSize": {
                    "value": 12,
                    "unit": "Number",
                    "attribute": "fine litter sample size"
                  }
                },
                "foi.observations": {
                  "plantFuelDryBiomass": [
                    {
                      "observableProperty": "plant fuel dry biomass",
                      "value": 478.25,
                      "unit": "Gram per Square Metre",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "plant fuel dry biomass",
                      "value": 478.25,
                      "unit": "Gram per Square Metre",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "plant fuel dry biomass",
                      "value": 478.25,
                      "unit": "Gram per Square Metre",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "plant fuel dry biomass",
                      "value": 478.25,
                      "unit": "Gram per Square Metre",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "plant fuel dry biomass",
                      "value": 478.25,
                      "unit": "Gram per Square Metre",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "plant fuel dry biomass",
                      "value": 478.25,
                      "unit": "Gram per Square Metre",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    }
                  ],
                  "fuelLoadMean": [
                    {
                      "observableProperty": "fuel load mean",
                      "value": 1.675,
                      "unit": "Tonne per Hectare",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "fuel load mean",
                      "value": 1.675,
                      "unit": "Tonne per Hectare",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "fuel load mean",
                      "value": 1.675,
                      "unit": "Tonne per Hectare",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "fuel load mean",
                      "value": 1.675,
                      "unit": "Tonne per Hectare",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "fuel load mean",
                      "value": 1.675,
                      "unit": "Tonne per Hectare",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "fuel load mean",
                      "value": 1.675,
                      "unit": "Tonne per Hectare",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    }
                  ],
                  "plantWaterContent": [
                    {
                      "observableProperty": "plant water content",
                      "value": 0.65,
                      "unit": "Percent",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "plant water content",
                      "value": 0.65,
                      "unit": "Percent",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "plant water content",
                      "value": 0.65,
                      "unit": "Percent",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "plant water content",
                      "value": 0.65,
                      "unit": "Percent",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "plant water content",
                      "value": 0.65,
                      "unit": "Percent",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "plant water content",
                      "value": 0.65,
                      "unit": "Percent",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    }
                  ]
                }
              },
              {
                "foi.id": "http://linked.data.gov.au/dataset/ausplots-forest/plant_litter_id-6",
                "foi.link": "https://ecoplots.tern.org.au/search?dataset=ausplots-forest&top_parent_site_id=ausplots-forest%2Fsite-nsfnnc0002&site_id=ausplots-forest%2Fsite-nsfnnc0002&feature_type=plant-litter",
                "foi.type": "plant litter",
                "metadata.link": null,
                "foi.attributes": {
                  "plantLitterfallProductionSampleSize": {
                    "value": 4,
                    "unit": "Number",
                    "attribute": "plant litterfall production sample size"
                  },
                  "leafLitterfallSampleSize": {
                    "value": 8,
                    "unit": "Number",
                    "attribute": "leaf litterfall sample size"
                  },
                  "plantFuelMatterType": {
                    "value": "Herb",
                    "unit": null,
                    "attribute": "plant fuel matter type"
                  },
                  "fineLitterSampleSize": {
                    "value": 12,
                    "unit": "Number",
                    "attribute": "fine litter sample size"
                  }
                },
                "foi.observations": {
                  "plantFuelDryBiomass": [
                    {
                      "observableProperty": "plant fuel dry biomass",
                      "value": 4.25,
                      "unit": "Gram per Square Metre",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "plant fuel dry biomass",
                      "value": 4.25,
                      "unit": "Gram per Square Metre",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "plant fuel dry biomass",
                      "value": 4.25,
                      "unit": "Gram per Square Metre",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "plant fuel dry biomass",
                      "value": 4.25,
                      "unit": "Gram per Square Metre",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "plant fuel dry biomass",
                      "value": 4.25,
                      "unit": "Gram per Square Metre",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "plant fuel dry biomass",
                      "value": 4.25,
                      "unit": "Gram per Square Metre",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    }
                  ],
                  "fuelLoadMean": [
                    {
                      "observableProperty": "fuel load mean",
                      "value": 0.0,
                      "unit": "Tonne per Hectare",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "fuel load mean",
                      "value": 0.0,
                      "unit": "Tonne per Hectare",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "fuel load mean",
                      "value": 0.0,
                      "unit": "Tonne per Hectare",
                      "resultTime": "2014-12-11T00:00:00",
                      "usedProcedure": "Fuel load survey",
                      "system": {}
                    },
                    {
                      "observableProperty": "fuel load mean",

In [23]:
ecoplots.clear()
ecoplots.select(dataset="TERN Ecosystem Surveillance").select(feature_type="plant population").select(observed_property="scientific name", site_id="SAAKAN0002")
ecoplots.get_sites()
#, site_id="NSFNNC0002")

          key                                                uri
0  SAAKAN0002  http://linked.data.gov.au/dataset/ausplots/sit...

In [24]:
parquet_data = ecoplots.get_data(dformat="parquet")
parquet_data

b'PAR1\x15\x04\x15>\x15BL\x15\x02\x15\x00\x12\x00\x00\x1fx\x1b\x00\x00\x00TERN Ecosystem Surveillance\x15\x00\x15\x12\x15\x16,\x15r\x15\x10\x15\x06\x15\x06\x1c6\x00(\x1bTERN Ecosystem Surveillance\x18\x1bTERN Ecosystem Surveillance\x11\x11\x00\x00\x00\t \x02\x00\x00\x00r\x01\x01r\x00\x15\x04\x15>\x15BL\x15\x02\x15\x00\x12\x00\x00\x1fx\x1b\x00\x00\x00TERN Ecosystem Surveillance\x15\x00\x15\x12\x15\x16,\x15r\x15\x10\x15\x06\x15\x06\x1c6\x00(\x1bTERN Ecosystem Surveillance\x18\x1bTERN Ecosystem Surveillance\x11\x11\x00\x00\x00\t \x02\x00\x00\x00r\x01\x01r\x00\x15\x04\x15\x1c\x15 L\x15\x02\x15\x00\x12\x00\x00\x0e4\n\x00\x00\x00SAAKAN0002\x15\x00\x15\x12\x15\x16,\x15r\x15\x10\x15\x06\x15\x06\x1c6\x00(\nSAAKAN0002\x18\nSAAKAN0002\x11\x11\x00\x00\x00\t \x02\x00\x00\x00r\x01\x01r\x00\x15\x04\x15\x10\x15\x14L\x15\x02\x15\x00\x12\x00\x00\x08\x1c\xbc?\xde\xabV\xd2A\xc0\x15\x00\x15\x12\x15\x16,\x15r\x15\x10\x15\x06\x15\x06\x1c\x18\x08\xbc?\xde\xabV\xd2A\xc0\x18\x08\xbc?\xde\xabV\xd2A\xc0\x16\x00(\x08\xbc?\xde\xabV\xd2A\xc0\x18\x08\xbc?\xde\xabV\xd2A\xc0\x11\x11\x00\x00\x00\t \x02\x00\x00\x00r\x01\x01r\x00\x15\x04\x15\x10\x15\x14L\x15\x02\x15\x00\x12\x00\x00\x08\x1c\xd0D\xd8\xf0\xf4&a@\x15\x00\x15\x12\x15\x16,\x15r\x15\x10\x15\x06\x15\x06\x1c\x18\x08\xd0D\xd8\xf0\xf4&a@\x18\x08\xd0D\xd8\xf0\xf4&a@\x16\x00(\x08\xd0D\xd8\xf0\xf4&a@\x18\x08\xd0D\xd8\xf0\xf4&a@\x11\x11\x00\x00\x00\t \x02\x00\x00\x00r\x01\x01r\x00\x15\x04\x150\x154L\x15\x06\x15\x00\x12\x00\x00\x18\\\x1c\xf03\x01\x00\x00\x00\x003>4\x01\x00\x00\x00\x00Re4\x01\x00\x00\x00\x00\x15\x00\x15\x1a\x15\x1e,\x15r\x15\x10\x15\x06\x15\x06\x1c\x18\x08Re4\x01\x00\x00\x00\x00\x18\x08\x1c\xf03\x01\x00\x00\x00\x00\x16\x00(\x08Re4\x01\x00\x00\x00\x00\x18\x08\x1c\xf03\x01\x00\x00\x00\x00\x11\x11\x00\x00\x00\r0\x02\x00\x00\x00r\x01\x02D\x00\x1c\x01\x12\x02\x15\x04\x15\x8a\x01\x15~L\x15\x06\x15\x00\x12\x00\x00EX\x13\x00\x00\x002018-10-20T15:01:09\t\x17\x0420\x01\x17(11T14:51:38\r\x17<1-10-26T10:57:59\x15\x00\x15\x1a\x15\x1e,\x15r\x15\x10\x15\x06\x15\x06\x1c6\x00(\x132021-10-26T10:57:59\x18\x132018-10-20T15:01:09\x11\x11\x00\x00\x00\r0\x02\x00\x00\x00r\x01\x02D\x00\x1c\x01\x12\x02\x15\x04\x15\x8a\x01\x15~L\x15\x06\x15\x00\x12\x00\x00EX\x13\x00\x00\x002018-10-20T15:01:09\t\x17\x0420\x01\x17(11T14:51:38\r\x17<1-10-26T10:57:59\x15\x00\x15\x1a\x15\x1e,\x15r\x15\x10\x15\x06\x15\x06\x1c6\x00(\x132021-10-26T10:57:59\x18\x132018-10-20T15:01:09\x11\x11\x00\x00\x00\r0\x02\x00\x00\x00r\x01\x02D\x00\x1c\x01\x12\x02\x15\x04\x15(\x15,L\x15\x02\x15\x00\x12\x00\x00\x14L\x10\x00\x00\x00plant population\x15\x00\x15\x12\x15\x16,\x15r\x15\x10\x15\x06\x15\x06\x1c6\x00(\x10plant population\x18\x10plant population\x11\x11\x00\x00\x00\t \x02\x00\x00\x00r\x01\x01r\x00\x15\x04\x15\xd2\\\x15\x9a\x0bL\x15r\x15\x00\x12\x00\x00\xa9.ts\x00\x00\x00http://linked.data.gov.au/\x01\x0c\x90set/ausplots/site_visit_id-58630-poin\x05\x0f,c-plant_popu\x01\x1flno-barcode-dead-tree-157748a\xfew\x00jw\x00 saa006856\xfee\x00\x82e\x00\x0c7609\xfee\x00\x8ae\x00\x0417\xfee\x00\x86e\x00\x08725\xfe\x0b\x02.\x0b\x02\x00e\xfe\x0b\x02\xd6\x0b\x02>w\x00E\x0b\xfe\xa6\x01>\xa6\x01Ze\x00\xfe\xa6\x016\xa6\x01Ve\x00\xfe\xa6\x01:\xa6\x01\x00n\xfe\xa6\x01\xd6\xa6\x01>w\x00\xfe\xa6\x01R\xa6\x01Ze\x00\xfe\xa6\x016\xa6\x01Ve\x00\x0c725t\xfe\xe0\x04\x9d\xe0\x00n>\x0c\x02jX\x05\x00b\xfex\x00nx\x00%\xa8\xa1Y\xfef\x00\x86f\x00a\xb4\xfef\x00\x8ef\x00\x0417\xfef\x00\x8af\x00\xfe\x10\x02>\x10\x02\x00w\xa6\xb7\x03\xfe\xde\x002\xde\x00>x\x00E\x10\xfe\xaa\x01B\xaa\x01Vf\x00\x08725\xfe\x05\x07.\x05\x07\x00s:C\x01\x05\xcbA\xdb\xfee\x00\x82e\x00!0\xfee\x00\x8ae\x00\x0417\xfe\x83\x04.\x83\x04\x00s\xfe\x83\x04\xda\x83\x04Bx\x00%\xa8!C\xfe\xd9\x02.\xd9\x02^f\x00\xfe\x1d\x046\x1d\x04Zf\x00\xfe\x1d\x04:\x1d\x04\x00s>?\x03\xfe-\x06\x9a-\x06Bx\x00\xfe\xaa\x01V\xaa\x01>\xde\x00\rf\x0417\xfe\xbd\n.\xbd\n>e\x00jC\x01\xfe\xca\x03.\xca\x03>w\x00\r\xdc\xfec\x0c6c\x0cZe\x00\xee\x17\t\x12\x17\t\x08876f\t\x0e\x01\xca\x0c1477\xfe^\x052e\x00>\x93\x04\te\x08640\xfa\x94\x012e\x00N\xe1\t\x05\xca\xfa\x80\x046e\x00V\xcb\x00\x08770\xfef\x00\x92f\x00\xfe\xcc\x006\xcc\x00Na\x02!2\xfe\x97\x012\x97\x01N\xbf\x07\x001\xfe\xfc\x01>\xfc\x01Ve\x00\x007\xfe0\x0160\x01R\x16\x06\x05\xcb\xfe\xfc\x01.\xfc\x01Zf\x00\xfe\xcc\x00\x96\xcc\x00\x0478\xfe\x87\n2.\x03R\x04\x06\xfe2\x01F2\x01Z\xc8\x02\x008\xfe\xf3\x052\xcc\x00Ze\x00\xfe)\x05\x0c9159\xb9\x8eR^\x04\x08747\xfa\xca\x00\x92e\x00\xfe\xfb\x016e\x00V)\x05\x01\xcb\xf6-\x03:f\x00R\x96\x01\x01f\xf6Z\x066f\x00R^\x04\x007\xfe1\x01:1\x01V\xf8\x03\x01\xcb\xfe1\x01.1\x01^f\x00\xfe\xfd\x016\xfd\x01V\x92\x03!2\xfe\x97\x01.\x97\x01Z\xfc\x01\x0488\x15\x00\x15p\x15t,\x15r\x15\x10\x15\x06\x15\x06\x1c6\x00(ahttp://linked.data.gov.au/dataset/ausplots/site_visit_id-59159-point_id-w-plant_popu_id-saa017488\x18shttp://linked.data.gov.au/dataset/ausplots/site_visit_id-58630-point_id-c-plant_popu_id-no-barcode-dead-tree-157748\x11\x11\x00\x00\x008\xdc\x02\x00\x00\x00r\x01\x06\x11@ \x0cDa\x1cH\xa2,L\xe3<P$MTe]X\xa6m\\\xe7}`(\x8edi\x9eh\xaa\xael\xeb\xbep,\xcftm\xdf8\x00\x00\x00\x00\x00\x15\x04\x15|\x15~L\x15\x02\x15\x00\x12\x00\x00>t:\x00\x00\x00http://linked.data.gov.au/\x01\x0clset/ausplots/site-saakan0002\x15\x00\x15\x12\x15\x16,\x15r\x15\x10\x15\x06\x15\x06\x1c6\x00(:http://linked.data.gov.au/dataset/ausplots/site-saakan0002\x18:http://linked.data.gov.au/dataset/ausplots/site-saakan0002\x11\x11\x00\x00\x00\t \x02\x00\x00\x00r\x01\x01r\x00\x15\x04\x15\xda\x02\x15\xde\x02L\x15\x0c\x15\x00\x12\x00\x00\xad\x01\xf0\x90\x0f\x00\x00\x00Dead Tree/Shrub%\x00\x00\x00Xanthorrhoea semiplana subsp. tateana\x12\x00\x00\x00Eucalyptus odorata\x12\x00\x00\x00Melaleuca uncinata\x1a\x00\x00\x00Allocasuarina verticillata#\x00\x00\x00Eucalyp\x01J\x10clado\x01\x0e8x subsp. crassa\x15\x00\x15@\x15D,\x15r\x15\x10\x15\x06\x15\x06\x1c6\x00(%Xanthorrhoea semiplana subsp. tateana\x18\x1aAllocasuarina verticillata\x11\x11\x00\x00\x00 |\x02\x00\x00\x00r\x01\x03\x11\x88Fh\x84FD#\xc4h\xd0\x08\rZ\x1a\x86M\xb3.,Y\xb6\x05\x00\x00\x15\x04\x15b\x15ZL\x15\x12\x15\x00\x12\x00\x001\x10\x01\x00\x00\x00C\x01\x05\x00E\x01\x05\x18N\x02\x00\x00\x00NE\x05\x06\x00W\x01\x11\x00S\x01\x0b0SE\x02\x00\x00\x00SW\x01\x00\x00\x00W\x15\x00\x15P\x15T,\x15r\x15\x10\x15\x06\x15\x06\x1c6\x00(\x01W\x18\x01C\x11\x11\x00\x00\x00(\x9c\x02\x00\x00\x00r\x01\x04\x11\x00\x00\x10\x11!"233DTUffw\x87\x88\x102CUfv\x87\x11Cev\x08\x00\x00\x00\x15\x04\x15\x8a\x01\x15hL\x15\x06\x15\x00\x12\x00\x00ED\x13\x00\x00\x002018-10-20T00:\x05\x03\t\x17\x0420\x01\x17\x0411>\x17\x00<1-10-26T00:00:00\x15\x00\x15\x1a\x15\x1e,\x15r\x15\x10\x15\x06\x15\x06\x1c6\x00(\x132021-10-26T00:00:00\x18\x132018-10-20T00:00:00\x11\x11\x00\x00\x00\r0\x02\x00\x00\x00r\x01\x02D\x00\x1c\x01\x12\x02\x15\x04\x15\xa4\x01\x15\xaa\x01L\x15\x02\x15\x00\x12\x00\x00R\xf0QN\x00\x00\x00http://linked.data.gov.au/def/ausplots-cv/1d39b897-d6d3-40e9-8113-8ebeab2cd38e\x15\x00\x15\x12\x15\x16,\x15r\x15\x10\x15\x06\x15\x06\x1c6\x00(Nhttp://linked.data.gov.au/def/ausplots-cv/1d39b897-d6d3-40e9-8113-8ebeab2cd38e\x18Nhttp://linked.data.gov.au/def/ausplots-cv/1d39b897-d6d3-40e9-8113-8ebeab2cd38e\x11\x11\x00\x00\x00\t \x02\x00\x00\x00r\x01\x01r\x00\x15\x04\x19\xfc\x105\x00\x18\x06schema\x15\x1e\x00\x15\x0c%\x02\x18\x0cdatasetTitle%\x00L\x1c\x00\x00\x00\x15\x0c%\x02\x18\x0cprojectTitle%\x00L\x1c\x00\x00\x00\x15\x0c%\x02\x18\x08siteName%\x00L\x1c\x00\x00\x00\x15\n%\x02\x18\x0flatitude_Degree\x00\x15\n%\x02\x18\x10longitude_Degree\x00\x15\x04%\x02\x18\rsiteVisitName\x00\x15\x0c%\x02\x18\x12siteVisitStartDate%\x00L\x1c\x00\x00\x00\x15\x0c%\x02\x18\x10siteVisitEndDate%\x00L\x1c\x00\x00\x00\x15\x0c%\x02\x18\x0bfeatureType%\x00L\x1c\x00\x00\x00\x15\x0c%\x02\x18\tfeatureId%\x00L\x1c\x00\x00\x00\x15\x0c%\x02\x18\x0fparentFeatureId%\x00L\x1c\x00\x00\x00\x15\x0c%\x02\x18\x0escientificName%\x00L\x1c\x00\x00\x00\x15\x0c%\x02\x18\x17basalSweepSamplingPoint%\x00L\x1c\x00\x00\x00\x15\x0c%\x02\x18\x18scientificNameResultTime%\x00L\x1c\x00\x00\x00\x15\x0c%\x02\x18\x14scientificNameMethod%\x00L\x1c\x00\x00\x00\x16r\x19\x1c\x19\xfc\x0f&\x00\x1c\x15\x0c\x195\x00\x06\x10\x19\x18\x0cdatasetTitle\x15\x02\x16r\x16\x8e\x02\x16\x96\x02&f&\x08\x1c6\x00(\x1bTERN Ecosystem Surveillance\x18\x1bTERN Ecosystem Surveillance\x11\x11\x00\x19,\x15\x04\x15\x00\x15\x02\x00\x15\x00\x15\x10\x15\x02\x00<\x16\x86\x18\x19\x06\x19&\x00r\x00\x00\x00&\x00\x1c\x15\x0c\x195\x00\x06\x10\x19\x18\x0cprojectTitle\x15\x02\x16r\x16\x8e\x02\x16\x96\x02&\xfc\x02&\x9e\x02\x1c6\x00(\x1bTERN Ecosystem Surveillance\x18\x1bTERN Ecosystem Surveillance\x11\x11\x00\x19,\x15\x04\x15\x00\x15\x02\x00\x15\x00\x15\x10\x15\x02\x00<\x16\x86\x18\x19\x06\x19&\x00r\x00\x00\x00&\x00\x1c\x15\x0c\x195\x00\x06\x10\x19\x18\x08siteName\x15\x02\x16r\x16\xa8\x01\x16\xb0\x01&\xf0\x04&\xb4\x04\x1c6\x00(\nSAAKAN0002\x18\nSAAKAN0002\x11\x11\x00\x19,\x15\x04\x15\x00\x15\x02\x00\x15\x00\x15\x10\x15\x02\x00<\x16\xf4\x08\x19\x06\x19&\x00r\x00\x00\x00&\x00\x1c\x15\n\x195\x00\x06\x10\x19\x18\x0flatitude_Degree\x15\x02\x16r\x16\xbc\x01\x16\xc4\x01&\x94\x06&\xe4\x05\x1c\x18\x08\xbc?\xde\xabV\xd2A\xc0\x18\x08\xbc?\xde\xabV\xd2A\xc0\x16\x00(\x08\xbc?\xde\xabV\xd2A\xc0\x18\x08\xbc?\xde\xabV\xd2A\xc0\x11\x11\x00\x19,\x15\x04\x15\x00\x15\x02\x00\x15\x00\x15\x10\x15\x02\x00<)\x06\x19&\x00r\x00\x00\x00&\x00\x1c\x15\n\x195\x00\x06\x10\x19\x18\x10longitude_Degree\x15\x02\x16r\x16\xbc\x01\x16\xc4\x01&\xd8\x07&\xa8\x07\x1c\x18\x08\xd0D\xd8\xf0\xf4&a@\x18\x08\xd0D\xd8\xf0\xf4&a@\x16\x00(\x08\xd0D\xd8\xf0\xf4&a@\x18\x08\xd0D\xd8\xf0\xf4&a@\x11\x11\x00\x19,\x15\x04\x15\x00\x15\x02\x00\x15\x00\x15\x10\x15\x02\x00<)\x06\x19&\x00r\x00\x00\x00&\x00\x1c\x15\x04\x195\x00\x06\x10\x19\x18\rsiteVisitName\x15\x02\x16r\x16\xe4\x01\x16\xec\x01&\xbc\t&\xec\x08\x1c\x18\x08Re4\x01\x00\x00\x00\x00\x18\x08\x1c\xf03\x01\x00\x00\x00\x00\x16\x00(\x08Re4\x01\x00\x00\x00\x00\x18\x08\x1c\xf03\x01\x00\x00\x00\x00\x11\x11\x00\x19,\x15\x04\x15\x00\x15\x02\x00\x15\x00\x15\x10\x15\x02\x00<)\x06\x19&\x00r\x00\x00\x00&\x00\x1c\x15\x0c\x195\x00\x06\x10\x19\x18\x12siteVisitStartDate\x15\x02\x16r\x16\xc4\x02\x16\xbc\x02&\xf4\x0b&\xd8\n\x1c6\x00(\x132021-10-26T10:57:59\x18\x132018-10-20T15:01:09\x11\x11\x00\x19,\x15\x04\x15\x00\x15\x02\x00\x15\x00\x15\x10\x15\x02\x00<\x16\xf6\x10\x19\x06\x19&\x00r\x00\x00\x00&\x00\x1c\x15\x0c\x195\x00\x06\x10\x19\x18\x10siteVisitEndDate\x15\x02\x16r\x16\xc4\x02\x16\xbc\x02&\xb0\x0e&\x94\r\x1c6\x00(\x132021-10-26T10:57:59\x18\x132018-10-20T15:01:09\x11\x11\x00\x19,\x15\x04\x15\x00\x15\x02\x00\x15\x00\x15\x10\x15\x02\x00<\x16\xf6\x10\x19\x06\x19&\x00r\x00\x00\x00&\x00\x1c\x15\x0c\x195\x00\x06\x10\x19\x18\x0bfeatureType\x15\x02\x16r\x16\xcc\x01\x16\xd4\x01&\x98\x10&\xd0\x0f\x1c6\x00(\x10plant population\x18\x10plant population\x11\x11\x00\x19,\x15\x04\x15\x00\x15\x02\x00\x15\x00\x15\x10\x15\x02\x00<\x16\xa0\x0e\x19\x06\x19&\x00r\x00\x00\x00&\x00\x1c\x15\x0c\x195\x00\x06\x10\x19\x18\tfeatureId\x15\x02\x16r\x16\xc0a\x16\x8c\x10&\xde\x1c&\xa4\x11\x1c6\x00(ahttp://linked.data.gov.au/dataset/ausplots/site_visit_id-59159-point_id-w-plant_popu_id-saa017488\x18shttp://linked.data.gov.au/dataset/ausplots/site_visit_id-58630-point_id-c-plant_popu_id-no-barcode-dead-tree-157748\x11\x11\x00\x19,\x15\x04\x15\x00\x15\x02\x00\x15\x00\x15\x10\x15\x02\x00<\x16\x8aY\x19\x06\x19&\x00r\x00\x00\x00&\x00\x1c\x15\x0c\x195\x00\x06\x10\x19\x18\x0fparentFeatureId\x15\x02\x16r\x16\xc8\x03\x16\xce\x03&\xca"&\xb0!\x1c6\x00(:http://linked.data.gov.au/dataset/ausplots/site-saakan0002\x18:http://linked.data.gov.au/dataset/ausplots/site-saakan0002\x11\x11\x00\x19,\x15\x04\x15\x00\x15\x02\x00\x15\x00\x15\x10\x15\x02\x00<\x16\xd43\x19\x06\x19&\x00r\x00\x00\x00&\x00\x1c\x15\x0c\x195\x00\x06\x10\x19\x18\x0escientificName\x15\x02\x16r\x16\xee\x04\x16\xf6\x04&\xfc\'&\xfe$\x1c6\x00(%Xanthorrhoea semiplana subsp. tateana\x18\x1aAllocasuarina verticillata\x11\x11\x00\x19,\x15\x04\x15\x00\x15\x02\x00\x15\x00\x15\x10\x15\x02\x00<\x16\x9c\x16\x19\x06\x19&\x00r\x00\x00\x00&\x00\x1c\x15\x0c\x195\x00\x06\x10\x19\x18\x17basalSweepSamplingPoint\x15\x02\x16r\x16\x88\x02\x16\x84\x02&\xea*&\xf4)\x1c6\x00(\x01W\x18\x01C\x11\x11\x00\x19,\x15\x04\x15\x00\x15\x02\x00\x15\x00\x15\x10\x15\x02\x00<\x16\xaa\x01\x19\x06\x19&\x00r\x00\x00\x00&\x00\x1c\x15\x0c\x195\x00\x06\x10\x19\x18\x18scientificNameResultTime\x15\x02\x16r\x16\xc4\x02\x16\xa6\x02&\xfe,&\xf8+\x1c6\x00(\x132021-10-26T00:00:00\x18\x132018-10-20T00:00:00\x11\x11\x00\x19,\x15\x04\x15\x00\x15\x02\x00\x15\x00\x15\x10\x15\x02\x00<\x16\xf6\x10\x19\x06\x19&\x00r\x00\x00\x00&\x00\x1c\x15\x0c\x195\x00\x06\x10\x19\x18\x14scientificNameMethod\x15\x02\x16r\x16\xc4\x04\x16\xce\x04&\xe8/&\x9e.\x1c6\x00(Nhttp://linked.data.gov.au/def/ausplots-cv/1d39b897-d6d3-40e9-8113-8ebeab2cd38e\x18Nhttp://linked.data.gov.au/def/ausplots-cv/1d39b897-d6d3-40e9-8113-8ebeab2cd38e\x11\x11\x00\x19,\x15\x04\x15\x00\x15\x02\x00\x15\x00\x15\x10\x15\x02\x00<\x16\xbcE\x19\x06\x19&\x00r\x00\x00\x00\x16\xfa\x83\x01\x16r&\x08\x16\xe42\x00\x19,\x18\x06pandas\x18\xbc\x10{"index_columns": [], "column_indexes": [], "columns": [{"name": "datasetTitle", "field_name": "datasetTitle", "pandas_type": "unicode", "numpy_type": "object", "metadata": null}, {"name": "projectTitle", "field_name": "projectTitle", "pandas_type": "unicode", "numpy_type": "object", "metadata": null}, {"name": "siteName", "field_name": "siteName", "pandas_type": "unicode", "numpy_type": "object", "metadata": null}, {"name": "latitude_Degree", "field_name": "latitude_Degree", "pandas_type": "float64", "numpy_type": "float64", "metadata": null}, {"name": "longitude_Degree", "field_name": "longitude_Degree", "pandas_type": "float64", "numpy_type": "float64", "metadata": null}, {"name": "siteVisitName", "field_name": "siteVisitName", "pandas_type": "int64", "numpy_type": "int64", "metadata": null}, {"name": "siteVisitStartDate", "field_name": "siteVisitStartDate", "pandas_type": "unicode", "numpy_type": "object", "metadata": null}, {"name": "siteVisitEndDate", "field_name": "siteVisitEndDate", "pandas_type": "unicode", "numpy_type": "object", "metadata": null}, {"name": "featureType", "field_name": "featureType", "pandas_type": "unicode", "numpy_type": "object", "metadata": null}, {"name": "featureId", "field_name": "featureId", "pandas_type": "unicode", "numpy_type": "object", "metadata": null}, {"name": "parentFeatureId", "field_name": "parentFeatureId", "pandas_type": "unicode", "numpy_type": "object", "metadata": null}, {"name": "scientificName", "field_name": "scientificName", "pandas_type": "unicode", "numpy_type": "object", "metadata": null}, {"name": "basalSweepSamplingPoint", "field_name": "basalSweepSamplingPoint", "pandas_type": "unicode", "numpy_type": "object", "metadata": null}, {"name": "scientificNameResultTime", "field_name": "scientificNameResultTime", "pandas_type": "unicode", "numpy_type": "object", "metadata": null}, {"name": "scientificNameMethod", "field_name": "scientificNameMethod", "pandas_type": "unicode", "numpy_type": "object", "metadata": null}], "attributes": {}, "creator": {"library": "pyarrow", "version": "25.0.1"}, "pandas_version": "3.0.5"}\x00\x18\x0cARROW:schema\x18\x8c /////wAMAAAQAAAAAAAKAA4ABgAFAAgACgAAAAABBAAQAAAAAAAKAAwAAAAEAAgACgAAAHQIAAAEAAAAAQAAAAwAAAAIAAwABAAIAAgAAABMCAAABAAAADwIAAB7ImluZGV4X2NvbHVtbnMiOiBbXSwgImNvbHVtbl9pbmRleGVzIjogW10sICJjb2x1bW5zIjogW3sibmFtZSI6ICJkYXRhc2V0VGl0bGUiLCAiZmllbGRfbmFtZSI6ICJkYXRhc2V0VGl0bGUiLCAicGFuZGFzX3R5cGUiOiAidW5pY29kZSIsICJudW1weV90eXBlIjogIm9iamVjdCIsICJtZXRhZGF0YSI6IG51bGx9LCB7Im5hbWUiOiAicHJvamVjdFRpdGxlIiwgImZpZWxkX25hbWUiOiAicHJvamVjdFRpdGxlIiwgInBhbmRhc190eXBlIjogInVuaWNvZGUiLCAibnVtcHlfdHlwZSI6ICJvYmplY3QiLCAibWV0YWRhdGEiOiBudWxsfSwgeyJuYW1lIjogInNpdGVOYW1lIiwgImZpZWxkX25hbWUiOiAic2l0ZU5hbWUiLCAicGFuZGFzX3R5cGUiOiAidW5pY29kZSIsICJudW1weV90eXBlIjogIm9iamVjdCIsICJtZXRhZGF0YSI6IG51bGx9LCB7Im5hbWUiOiAibGF0aXR1ZGVfRGVncmVlIiwgImZpZWxkX25hbWUiOiAibGF0aXR1ZGVfRGVncmVlIiwgInBhbmRhc190eXBlIjogImZsb2F0NjQiLCAibnVtcHlfdHlwZSI6ICJmbG9hdDY0IiwgIm1ldGFkYXRhIjogbnVsbH0sIHsibmFtZSI6ICJsb25naXR1ZGVfRGVncmVlIiwgImZpZWxkX25hbWUiOiAibG9uZ2l0dWRlX0RlZ3JlZSIsICJwYW5kYXNfdHlwZSI6ICJmbG9hdDY0IiwgIm51bXB5X3R5cGUiOiAiZmxvYXQ2NCIsICJtZXRhZGF0YSI6IG51bGx9LCB7Im5hbWUiOiAic2l0ZVZpc2l0TmFtZSIsICJmaWVsZF9uYW1lIjogInNpdGVWaXNpdE5hbWUiLCAicGFuZGFzX3R5cGUiOiAiaW50NjQiLCAibnVtcHlfdHlwZSI6ICJpbnQ2NCIsICJtZXRhZGF0YSI6IG51bGx9LCB7Im5hbWUiOiAic2l0ZVZpc2l0U3RhcnREYXRlIiwgImZpZWxkX25hbWUiOiAic2l0ZVZpc2l0U3RhcnREYXRlIiwgInBhbmRhc190eXBlIjogInVuaWNvZGUiLCAibnVtcHlfdHlwZSI6ICJvYmplY3QiLCAibWV0YWRhdGEiOiBudWxsfSwgeyJuYW1lIjogInNpdGVWaXNpdEVuZERhdGUiLCAiZmllbGRfbmFtZSI6ICJzaXRlVmlzaXRFbmREYXRlIiwgInBhbmRhc190eXBlIjogInVuaWNvZGUiLCAibnVtcHlfdHlwZSI6ICJvYmplY3QiLCAibWV0YWRhdGEiOiBudWxsfSwgeyJuYW1lIjogImZlYXR1cmVUeXBlIiwgImZpZWxkX25hbWUiOiAiZmVhdHVyZVR5cGUiLCAicGFuZGFzX3R5cGUiOiAidW5pY29kZSIsICJudW1weV90eXBlIjogIm9iamVjdCIsICJtZXRhZGF0YSI6IG51bGx9LCB7Im5hbWUiOiAiZmVhdHVyZUlkIiwgImZpZWxkX25hbWUiOiAiZmVhdHVyZUlkIiwgInBhbmRhc190eXBlIjogInVuaWNvZGUiLCAibnVtcHlfdHlwZSI6ICJvYmplY3QiLCAibWV0YWRhdGEiOiBudWxsfSwgeyJuYW1lIjogInBhcmVudEZlYXR1cmVJZCIsICJmaWVsZF9uYW1lIjogInBhcmVudEZlYXR1cmVJZCIsICJwYW5kYXNfdHlwZSI6ICJ1bmljb2RlIiwgIm51bXB5X3R5cGUiOiAib2JqZWN0IiwgIm1ldGFkYXRhIjogbnVsbH0sIHsibmFtZSI6ICJzY2llbnRpZmljTmFtZSIsICJmaWVsZF9uYW1lIjogInNjaWVudGlmaWNOYW1lIiwgInBhbmRhc190eXBlIjogInVuaWNvZGUiLCAibnVtcHlfdHlwZSI6ICJvYmplY3QiLCAibWV0YWRhdGEiOiBudWxsfSwgeyJuYW1lIjogImJhc2FsU3dlZXBTYW1wbGluZ1BvaW50IiwgImZpZWxkX25hbWUiOiAiYmFzYWxTd2VlcFNhbXBsaW5nUG9pbnQiLCAicGFuZGFzX3R5cGUiOiAidW5pY29kZSIsICJudW1weV90eXBlIjogIm9iamVjdCIsICJtZXRhZGF0YSI6IG51bGx9LCB7Im5hbWUiOiAic2NpZW50aWZpY05hbWVSZXN1bHRUaW1lIiwgImZpZWxkX25hbWUiOiAic2NpZW50aWZpY05hbWVSZXN1bHRUaW1lIiwgInBhbmRhc190eXBlIjogInVuaWNvZGUiLCAibnVtcHlfdHlwZSI6ICJvYmplY3QiLCAibWV0YWRhdGEiOiBudWxsfSwgeyJuYW1lIjogInNjaWVudGlmaWNOYW1lTWV0aG9kIiwgImZpZWxkX25hbWUiOiAic2NpZW50aWZpY05hbWVNZXRob2QiLCAicGFuZGFzX3R5cGUiOiAidW5pY29kZSIsICJudW1weV90eXBlIjogIm9iamVjdCIsICJtZXRhZGF0YSI6IG51bGx9XSwgImF0dHJpYnV0ZXMiOiB7fSwgImNyZWF0b3IiOiB7ImxpYnJhcnkiOiAicHlhcnJvdyIsICJ2ZXJzaW9uIjogIjI1LjAuMSJ9LCAicGFuZGFzX3ZlcnNpb24iOiAiMy4wLjUifQAAAAAGAAAAcGFuZGFzAAAPAAAAKAMAAOQCAAC0AgAAdAIAADgCAAD0AQAAvAEAAIQBAABUAQAAJAEAAPAAAAC8AAAAgAAAAEAAAAAEAAAAJP3//wAAAQUQAAAAKAAAAAQAAAAAAAAAFAAAAHNjaWVudGlmaWNOYW1lTWV0aG9kAAAAABz9//9c/f//AAABBRAAAAAsAAAABAAAAAAAAAAYAAAAc2NpZW50aWZpY05hbWVSZXN1bHRUaW1lAAAAAFj9//+Y/f//AAABBRAAAAAoAAAABAAAAAAAAAAXAAAAYmFzYWxTd2VlcFNhbXBsaW5nUG9pbnQAkP3//9D9//8AAAEFEAAAACAAAAAEAAAAAAAAAA4AAABzY2llbnRpZmljTmFtZQAAwP3//wD+//8AAAEFEAAAACAAAAAEAAAAAAAAAA8AAABwYXJlbnRGZWF0dXJlSWQA8P3//zD+//8AAAEFEAAAABwAAAAEAAAAAAAAAAkAAABmZWF0dXJlSWQAAAAc/v//XP7//wAAAQUQAAAAHAAAAAQAAAAAAAAACwAAAGZlYXR1cmVUeXBlAEj+//+I/v//AAABBRAAAAAkAAAABAAAAAAAAAAQAAAAc2l0ZVZpc2l0RW5kRGF0ZQAAAAB8/v//vP7//wAAAQUQAAAAJAAAAAQAAAAAAAAAEgAAAHNpdGVWaXNpdFN0YXJ0RGF0ZQAAsP7///D+//8AAAECEAAAACgAAAAEAAAAAAAAAA0AAABzaXRlVmlzaXROYW1lAAAACAAMAAgABwAIAAAAAAAAAUAAAAAw////AAABAxAAAAAkAAAABAAAAAAAAAAQAAAAbG9uZ2l0dWRlX0RlZ3JlZQAAAADK////AAACAGj///8AAAEDEAAAACgAAAAEAAAAAAAAAA8AAABsYXRpdHVkZV9EZWdyZWUAAAAGAAgABgAGAAAAAAACAKT///8AAAEFEAAAABwAAAAEAAAAAAAAAAgAAABzaXRlTmFtZQAAAACQ////0P///wAAAQUQAAAAIAAAAAQAAAAAAAAADAAAAHByb2plY3RUaXRsZQAAAADA////EAAUAAgABgAHAAwAAAAQABAAAAAAAAEFEAAAACQAAAAEAAAAAAAAAAwAAABkYXRhc2V0VGl0bGUAAAAABAAEAAQAAAA=\x00\x18 parquet-cpp-arrow version 25.0.1\x19\xfc\x0f\x1c\x00\x00\x1c\x00\x00\x1c\x00\x00\x1c\x00\x00\x1c\x00\x00\x1c\x00\x00\x1c\x00\x00\x1c\x00\x00\x1c\x00\x00\x1c\x00\x00\x1c\x00\x00\x1c\x00\x00\x1c\x00\x00\x1c\x00\x00\x1c\x00\x00\x00\xe9"\x00\x00PAR1'