# EcoPlots Python Library
# Use case 2 - Plant occurrence - vegetation height

In [3]:
from terndata.ecoplots import EcoPlots
ecoplots = EcoPlots()

# Display the client information
print(ecoplots)

EcoPlots initialized in observations mode.
╔══════════════════════════════════════════════════════════════════════════════╗
║ EcoPlots Observations                                                        ║
║ Version: 1.1.2                                                               ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ No filters applied                                                           ║
╚══════════════════════════════════════════════════════════════════════════════╝

In [4]:
ecoplots.select(feature_type="plant occurrence")
ecoplots.get_observed_properties()

,key,uri
0,scientific name,http://linked.data.gov.au/def/tern-cv/56195246...
1,plant growth form,http://linked.data.gov.au/def/tern-cv/f81aa91e...
2,in-canopy sky,http://linked.data.gov.au/def/tern-cv/9b2ab960...
3,plant mortality,http://linked.data.gov.au/def/tern-cv/cd11241d...
4,taxon,http://linked.data.gov.au/def/tern-cv/70646576...
5,plant height,http://linked.data.gov.au/def/tern-cv/09296da0...
6,IUCN Red List category,http://linked.data.gov.au/def/tern-cv/6f59a7ac...
7,EPBC Act conservation status,http://linked.data.gov.au/def/tern-cv/fd98815c...

In [5]:

# Apply some filters
ecoplots.select(feature_type="plant occurrence").select(observed_property=["scientific name", "plant height", "growth form"])
# List available data sources
ecoplots.get_datasources()

⚠️  Warning: Value 'growth form' for facet 'observed_property' corrected to 'plant growth form'.

                           key                                         uri
0  TERN Ecosystem Surveillance  http://linked.data.gov.au/dataset/ausplots

In [6]:
# Summarise the data before downloading it into a DataFrame
ecoplots.summary()

              metric    count
0       observations  1982865
1            dataset        1
2       feature_type        1
3  observed_property        3
4               site      812
5         site_visit     1086

In [5]:
ecoplots.select(site_id="NSTSYB0001")

EcoPlots 'observations'(filterset={'feature_type': ['plant occurrence'], 'observed_property': ['scientific name', 'plant height', 'plant growth form'], 'site_id': ['NSTSYB0001']}, query_filters={'feature_type': ['http://linked.data.gov.au/def/tern-cv/b311c0d3-4a1a-4932-a39c-f5cdc1afa611'], 'observed_property': ['http://linked.data.gov.au/def/tern-cv/f81aa91e-5f57-4e49-bc6e-4d821d1f9de2', 'http://linked.data.gov.au/def/tern-cv/09296da0-c645-4165-950c-780c21b3c140', 'http://linked.data.gov.au/def/tern-cv/56195246-ec5d-4050-a1c6-af786fbec715'], 'site_id': ['http://linked.data.gov.au/dataset/ausplots/site-nstsyb0001']},

In [6]:
# Summarise the data before downloading it into a DataFrame
ecoplots.summary()

              metric  count
0       observations   4773
1            dataset      1
2       feature_type      1
3  observed_property      3
4               site      1
5         site_visit      1

In [15]:
# Download the data into a DataFrame. By default, this will return a pandas DataFrame.
# The total ammount of data downloaded will be 244k rows. This may take a few moments.
df_plant = ecoplots.get_data()

In [19]:
# Display the first few rows of the DataFrame
df_plant.head()

,datasetTitle,projectTitle,siteName,transectName,latitude_Degree,longitude_Degree,siteVisitName,siteVisitStartDate,siteVisitEndDate,featureType,...,transectPoint,scientificNameResultTime,scientificNameMethod,plantGrowthForm,plantGrowthFormResultTime,plantGrowthFormMethod,plantHeight_metre,plantHeightResultTime,plantHeightMethod,geometry
0,TERN Ecosystem Surveillance,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-S5-N5,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,...,0.0,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,tree/palm,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,6.0,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,POINT (151.135 -33.67334)
1,TERN Ecosystem Surveillance,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-S5-N5,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,...,0.0,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,forb,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,0.2,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,POINT (151.135 -33.67334)
2,TERN Ecosystem Surveillance,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-S5-N5,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,...,1.0,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,tree/palm,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,6.0,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,POINT (151.135 -33.67334)
3,TERN Ecosystem Surveillance,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-S5-N5,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,...,N/A,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,tree/palm,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,5.0,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,POINT (151.135 -33.67334)
4,TERN Ecosystem Surveillance,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-S5-N5,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,...,3.0,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,tree/palm,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,N/A,N/A,N/A,POINT (151.135 -33.67334)

In [30]:
# Count occurrences of each scientific name, sorted in descending order (most frequent first)
df_plant.groupby(by=['plantGrowthForm']).size().sort_values(ascending=False)

plantGrowthForm
shrub            809
tree/palm        537
forb             163
sedge            100
vine               8
tussock grass      6
fern               3
shrub mallee       2
dtype: int64

In [31]:
# Count occurrences of each scientific name, sorted in descending order (most frequent first)
df_plant.groupby(by=['scientificName']).size().sort_values(ascending=False)

scientificName
Eucalyptus sparsifolia                        191
Corymbia gummifera                            172
Eucalyptus haemastoma                         163
Hemigenia purpurea                             89
Banksia ericifolia                             85
Banksia serrata                                70
Xanthorrhoea                                   65
Phyllota grandiflora                           65
Leucopogon microphyllus var. pilibundus        64
Actinotus minor                                62
Pultenaea tuberculata                          53
Leptospermum trinervium                        48
Calytrix tetragona                             47
Grevillea sericea                              45
Schoenus imberbis                              41
Lambertia formosa                              37
Dillwynia retorta                              31
Woollsia pungens                               30
Gompholobium grandiflorum                      30
Petrophile pulchella                           25
Grevillea buxifolia subsp. buxifolia           23
Indeterminate                                  21
Epacris microphylla                            20
Cyathochaeta                                   16
Caustis recurvata                              15
Hibbertia bracteata                            12
Platysace linearifolia                         11
Persoonia pinifolia                            10
Cassytha pubescens                              8
Hakea laevipes                                  7
Allocasuarina littoralis                        6
Anisopogon avenaceus                            6
Lomandra glauca                                 6
Banksia spinulosa                               6
Bossiaea ensata                                 5
Acacia myrtifolia                               5
Leptocarpus tenax                               4
Isopogon anemonifolius                          4
Lepyrodia cryptica                              3
Hakea sericea                                   3
Olax stricta                                    3
Hakea propinqua                                 3
Banksia oblongifolia                            3
Gleichenia dicarpa                              3
Annual Forb                                     2
Conospermum longifolium subsp. longifolium      2
Pultenaea linophylla                            2
Acacia suaveolens                               2
Angophora hispida                               2
Dead Tree/Shrub                                 1
Persoonia levis                                 1
dtype: int64

In [22]:
# transform plantHeight_metre to numeric, coerce errors to NaN
import pandas as pd
df_plant['plantHeight_metre'] = pd.to_numeric(df_plant['plantHeight_metre'], errors='coerce')
df_plant['plantHeight_metre'].dtype

dtype('float64')

In [ ]:
# Tallest plant individual for each scientific name
df_plant[['scientificName', 'plantHeight_metre']].loc[df_plant.groupby('scientificName')['plantHeight_metre'].idxmax()]

                                  scientificName  plantHeight_metre
625                            Acacia myrtifolia                0.7
977                            Acacia suaveolens                1.5
1273                             Actinotus minor                0.7
1548                    Allocasuarina littoralis                1.2
835                            Angophora hispida                1.3
32                          Anisopogon avenaceus                0.2
801                                  Annual Forb                0.1
494                           Banksia ericifolia                5.0
204                         Banksia oblongifolia                1.5
949                              Banksia serrata                7.0
188                            Banksia spinulosa                2.0
875                              Bossiaea ensata                0.8
677                           Calytrix tetragona                1.3
539                           Cassytha pubescens                0.9
521                            Caustis recurvata                0.9
317   Conospermum longifolium subsp. longifolium                0.7
1487                          Corymbia gummifera               11.0
1447                                Cyathochaeta                0.3
743                              Dead Tree/Shrub                1.1
664                            Dillwynia retorta                1.1
811                          Epacris microphylla                1.0
130                        Eucalyptus haemastoma                9.0
275                       Eucalyptus sparsifolia               10.0
543                           Gleichenia dicarpa                0.5
228                    Gompholobium grandiflorum                1.2
53          Grevillea buxifolia subsp. buxifolia                1.5
1023                           Grevillea sericea                2.2
762                               Hakea laevipes                2.3
112                              Hakea propinqua                2.0
833                                Hakea sericea                1.5
384                           Hemigenia purpurea                1.0
975                          Hibbertia bracteata                0.9
867                                Indeterminate                0.7
1356                      Isopogon anemonifolius                0.8
311                            Lambertia formosa                2.0
205                            Leptocarpus tenax                0.4
470                      Leptospermum trinervium                2.8
1265                          Lepyrodia cryptica                0.3
687      Leucopogon microphyllus var. pilibundus                0.8
428                              Lomandra glauca                0.1
1278                                Olax stricta                2.0
129                              Persoonia levis                0.2
522                          Persoonia pinifolia                1.7
971                         Petrophile pulchella                2.8
1077                        Phyllota grandiflora                1.5
497                       Platysace linearifolia                1.0
1257                        Pultenaea linophylla                0.7
1526                       Pultenaea tuberculata                1.8
742                            Schoenus imberbis                0.4
1241                            Woollsia pungens                1.1
1310                                Xanthorrhoea                1.0

In [25]:
# Group by growthForm and scientificName and calculate the average plant height for each growth form
df_plant.groupby(['plantGrowthForm'])['plantHeight_metre'].mean().reset_index()

  plantGrowthForm  plantHeight_metre
0            fern           0.433333
1            forb           0.329141
2           sedge           0.195900
3           shrub           0.814486
4    shrub mallee           1.200000
5       tree/palm           5.942523
6   tussock grass           0.101667
7            vine           0.481250

In [26]:
# Find the unique tallest plant from the dataframe
df_plant.loc[df_plant['plantHeight_metre'].idxmax()]

datasetTitle                                       TERN Ecosystem Surveillance
projectTitle                                       TERN Ecosystem Surveillance
siteName                                                            NSTSYB0001
transectName                                         NSTSYB0001-transect-W1-E1
latitude_Degree                                                      -33.67334
longitude_Degree                                                       151.135
siteVisitName                                                         20151111
siteVisitStartDate                                         2015-11-11T12:11:06
siteVisitEndDate                                           2015-11-11T12:11:06
featureType                                                   plant occurrence
featureId                    http://linked.data.gov.au/dataset/ausplots/sit...
scientificName                                              Corymbia gummifera
transectPoint                                                              N/A
scientificNameResultTime                                   2015-11-11T00:00:00
scientificNameMethod         http://linked.data.gov.au/def/ausplots-cv/1d39...
plantGrowthForm                                                      tree/palm
plantGrowthFormResultTime                                  2015-11-11T00:00:00
plantGrowthFormMethod        http://linked.data.gov.au/def/ausplots-cv/c5a3...
plantHeight_metre                                                         11.0
plantHeightResultTime                                      2015-11-11T00:00:00
plantHeightMethod            http://linked.data.gov.au/def/ausplots-cv/c5a3...
geometry                                             POINT (151.135 -33.67334)
Name: 1487, dtype: object

In [29]:
# Find the tallest plant in each growth form
df_plant.loc[df_plant.groupby('plantGrowthForm')['plantHeight_metre'].idxmax()]

,datasetTitle,projectTitle,siteName,transectName,latitude_Degree,longitude_Degree,siteVisitName,siteVisitStartDate,siteVisitEndDate,featureType,...,transectPoint,scientificNameResultTime,scientificNameMethod,plantGrowthForm,plantGrowthFormResultTime,plantGrowthFormMethod,plantHeight_metre,plantHeightResultTime,plantHeightMethod,geometry
543,TERN Ecosystem Surveillance,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-S4-N4,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,...,49.0,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,fern,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,0.5,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,POINT (151.135 -33.67334)
384,TERN Ecosystem Surveillance,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-N2-S2,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,...,N/A,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,forb,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,1.0,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,POINT (151.135 -33.67334)
521,TERN Ecosystem Surveillance,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-S4-N4,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,...,37.0,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,sedge,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,0.9,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,POINT (151.135 -33.67334)
488,TERN Ecosystem Surveillance,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-S4-N4,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,...,8.0,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,shrub,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,4.0,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,POINT (151.135 -33.67334)
835,TERN Ecosystem Surveillance,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-W5-E5,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,...,N/A,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,shrub mallee,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,1.3,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,POINT (151.135 -33.67334)
1487,TERN Ecosystem Surveillance,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-W1-E1,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,...,N/A,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,tree/palm,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,11.0,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,POINT (151.135 -33.67334)
32,TERN Ecosystem Surveillance,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-S5-N5,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,...,16.0,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,tussock grass,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,0.2,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,POINT (151.135 -33.67334)
539,TERN Ecosystem Surveillance,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-S4-N4,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,...,N/A,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,vine,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,0.9,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,POINT (151.135 -33.67334)